export enum OrderCancellationReason {
  CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  CUSTOMER_UNREACHABLE = 'CUSTOMER_UNREACHABLE',
  AGE_VERIFICATION_FAILED = 'AGE_VERIFICATION_FAILED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  DELIVERY_UNAVAILABLE = 'DELIVERY_UNAVAILABLE',
  OTHER = 'OTHER',
}
